name: flutter_demo
version: 1.0.0+1
publish_to: none
description: grid app using flutter
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # getx
  get: 4.6.5
  # 屏幕适配
  flutter_screenutil: ^5.8.4
  # 上拉加载、下拉刷新
  infinite_scroll_pagination: ^3.2.0
  # loading
  flutter_easyloading: ^3.0.5
  # http
  dio: ^5.3.1
  # 缓存
  shared_preferences: ^2.2.0
  # 网络图片缓存
  cached_network_image: ^3.2.3
  # 缓存
  flutter_cache_manager: ^3.3.1
  # 设备信息
  device_info_plus: ^9.0.2
  # 包信息
  package_info_plus: ^4.0.2
  # 路经查询
  path_provider: ^2.0.15
  # 权限相关
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

